import type { Metadata } from "next";
import localFont from "next/font/local";
import "keen-slider/keen-slider.min.css";
import "./globals.scss";
import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/SessionProvider";
import LayoutClient from "./layout.client";

const geistSans = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "a-studio-movie",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <SessionProvider session={session}>
          <LayoutClient>{children}</LayoutClient>
        </SessionProvider>
      </body>
    </html>
  );
}
